on: workflow_dispatch

jobs:
  build:
    uses: "zmkfirmware/zmk/.github/workflows/build-user-config.yml@main"
    with:
      build_matrix_path: "build.yaml"
      config_path: "config"
      fallback_binary: "bin"
      archive_name: "ergodox_firmware"
